- hosts: all
  become: yes
  tasks:
  - import_tasks: ./tasks/system/epel.yml
    when: ansible_distribution == 'CentOS'
  - import_tasks: ./tasks/system/packages.yml
  - import_tasks: ./tasks/app/app.yml
  - import_tasks: ./tasks/httpd/httpd.yml
