- hosts: all
  become: yes
  tasks:
  - name: upgrade all packages
    yum: name=* state=latest
  - name: ensure apache is at the latest version
    yum: name=httpd state=latest
  - name: ensure apache is running
    service: name=httpd state=started
  - name: ensure git is installed
    yum: name=git state=latest
  - name: ensure mod_wsgi is installed
    yum: name=mod_wsgi state=latest
  - name: ensure python2-pip is installed
    yum: name=python-pip state=latest