  - name: Upgrade all packages
    yum: 
      name: '*' 
      state: latest
  - name: Ensure necessary packages installed and up to date
    yum: 
      name:
        - python
        - python-pip
        - httpd 
        - mod_wsgi
      state: latest
  - name: Install flask with pip
    pip: 
      name: flask